const NEXT_TURN = 'nextTurn';
const NEXT_ROUND = 'nextRound';
const HAND_CARD_PLAY = 'handCardPlay';
const TABLE_CARD_PLAY_PLAYER_TARGET = 'tableCardPlayTargerPlayer';
const TABLE_CARD_PLAY_CARD_TARGET = 'tableCardPlayCardTarget';
const PLAYER_DAMAGE = 'playerDamage';
const TABLE_CARD_DAMAGE = 'tableCardDamage';
const ENEMY_TABLE_CARD_DAMAGE = 'enemyTableCardDamage';
const TABLE_CARD_DESTROY = 'tableCardDestroy';
const CLOSE_SOCKET = 'closeSocket';
const DISCONNECT = 'disconnect';
const NOT_ENOUGH_MANA = 'notEnoughMana';
const START_GAME = 'startGame';
const PLAYER_WIN = 'PLAYER_WIN';
const PLAYER_LOSE = 'PLAYER_LOSE';
const GET_DECK_CARD = 'GET_DECK_CARD';
const ENEMY_GET_DECK_CARD = 'ENEMY_GET_DECK_CARD';
const DESTROY_DECK_CARD = 'DESTROY_DECK_CARD';
const DESTROY_DECK_CARD_TIME = 1500;

const WIN = 'ПОБЕДА';
const LOSE = 'ПОРАЖЕНИЕ';

export {
  START_GAME,
  NEXT_TURN,
  NEXT_ROUND,
  HAND_CARD_PLAY,
  TABLE_CARD_PLAY_PLAYER_TARGET,
  TABLE_CARD_PLAY_CARD_TARGET,
  PLAYER_DAMAGE,
  TABLE_CARD_DAMAGE,
  TABLE_CARD_DESTROY,
  CLOSE_SOCKET,
  NOT_ENOUGH_MANA,
  DISCONNECT,
  ENEMY_TABLE_CARD_DAMAGE,
  PLAYER_WIN,
  PLAYER_LOSE,
  WIN,
  LOSE,
  GET_DECK_CARD,
  ENEMY_GET_DECK_CARD,
  DESTROY_DECK_CARD,
  DESTROY_DECK_CARD_TIME,
};
