openapi: 3.0.0
info:
  title:  Card Game
  description: card game with heroes and magic
  version: 1.0.0

servers:
  - url: /

components:
  schemas:
    User:
      type: object
      properties:
        user_id:
          type: integer
        name:
          type: string
        login:
          type: string
    Deck:
      properties:
        user_deck_id:
          type: integer
        user_id:
          type: integer
        name:
          type: string
        isinitial:
          type: boolean
        cards_count:
          type: integer
        cards:
          type: array
          items:
            $ref: "#/components/schemas/Card"
    Card:
      required:
        - title
      properties:
        id:
          type: integer
        name:
          type: string
        attack:
          type: integer
        manaCost:
          type: integer
        health: 
          type: integer
        isinitial:
          type: boolean
        isActive:
          type: boolean
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /users:
    get:
      tags:
        - Users
      summary: Get all users
      description: Gets all users (remove password from response)
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        401:
          $ref: '#/components/responses/UnauthorizedError'
    post:
      tags:
        - Users
      summary: Create user
      description: Creates a new user (remove password from response)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: example
              properties:
                name:
                  type: string
                  description: The user's name
                login:
                  type: string
                  description: The user's login
                password:
                  type: string
                  description: The user's password
              required:
                - name
      responses:
        200:
          description: The user has been created.
          content: 
            text/json:
              schema:
                type: integer
                title: user_id
        400:
          description: Bad request
        401:
          $ref: '#/components/responses/UnauthorizedError'
  /users/{userId}:
    parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - Users
      summary: Get user by ID
      description: Gets a user by ID
        e.g. “/users/123” (remove password from response)
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          description: User not found
    put:
      tags:
        - Users
      summary: Update a user
      description: Updates a user by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: example
              properties:
                name:
                  type: string
                  description: The user's name
                login:
                  type: string
                  description: The user's login
                password:
                  type: string
                  description: The user's password
              required:
                - name
      responses:
        200:
          description: The user has been updated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Bad request
        401:
          $ref: '#/components/responses/UnauthorizedError'
    delete:
      tags:
        - Users
      summary: Delete user
      description: Deletes user by ID. 
      responses:
        204:
          description: The user has been deleted
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          description: User not found
  /decks:
    get:
      tags:
        - Decks
      summary: Get all decks
      description: Returns all decks
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Deck"
        401:
          $ref: '#/components/responses/UnauthorizedError'
    post:
      tags:
        - Decks
      summary: Create deck
      description: Creates a new deck
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: example
              properties:
                user_id:
                  type: integer
                name:
                  type: string
                isinitial:
                  type: boolean
                cards:
                  type: array
                  items:
                    type: object
                    title: cardId
                    properties:
                      id:
                        type: integer
              required:
                - user_id
                - name
      responses:
        200:
          description: The deck has been created.
          content:
             text/json:
              schema:
                type: integer
                title: user_id
        400:
          description: Bad request
        401:
          $ref: '#/components/responses/UnauthorizedError'
  /decks/{deckId}:
    parameters:
      - name: deckId
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - Decks
      summary: Get deck by id
      description: Gets the Deck by ID (e.g. “/decks/123”)
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Deck"
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          description: Deck not found
    put:
      tags:
        - Decks
      summary: Update deck
      description: Updates a Deck by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: example
              properties:
                user_id:
                  type: integer
                name:
                  type: string
                isinitial:
                  type: boolean
                cards:
                  type: array
                  items:
                    type: object
                    title: cardId
                    properties:
                      id:
                        type: integer
              required:
                - user_id
                - name
      responses:
        200:
          description: The board has been updated.
          content:
             text/json:
              schema:
                $ref: "#/components/schemas/Deck"
        400:
          description: Bad request
        401:
          $ref: '#/components/responses/UnauthorizedError'
    delete:
      tags:
        - Decks
      summary: Delete deck
      description: Deletes a Deck by ID.
        
      responses:
        204:
          description: The deck has been deleted
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          description: Deck not found
  /decks/{deckId}/tasks:
    parameters:
      - name: deckId
        in: path
        required: true
        schema:
          type: string
    get:
      tags:
        - Card
      summary: Get Tasks by boardId
      description: Gets tasks by the Board ID
        (e.g. “/board/1/tasks”)
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Card"
        401:
          $ref: '#/components/responses/UnauthorizedError'
    post:
      tags:
        - Card
      summary: Create new task
      description: Creates a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: example
              properties:
                title:
                  type: string
                  description: The task's title
                order:
                  type: integer
                  description: The task's order
                description:
                  type: string
                userId:
                  type: string
                  description: The task's Assignee
                boardId:
                  type: string
                  description: Board ID
                columnId:
                  type: string
                  description: Column ID
              required:
                - title
                - order
                - boardId
                - columnId
      responses:
        200:
          description: The task has been created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Card"           
        400:
          description: Bad request
        401:
          $ref: '#/components/responses/UnauthorizedError'
  /decks/{deckId}/tasks/{taskId}:
    parameters:
      - name: deckId
        in: path
        required: true
        schema:
          type: string
      - name: taskId
        in: path
        required: true
        schema:
          type: string
    get:
      tags:
        - Card
      summary: Get Task by deckId and taskId
      description: Gets the Task by the deck's and task ID
        (e.g. “/deck/1/tasks/123”)
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Card"
        401:
          $ref: '#/components/responses/UnauthorizedError'
    put:
      tags:
        - Card
      summary: Update Task
      description: Updates the Task by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: example
              properties:
                id:
                  type: string
                  title: The task's ID
                title:
                  type: string
                  description: The task's title
                order:
                  type: integer
                  description: The task's order
                description:
                  type: string
                userId:
                  type: string
                  description: The task's Assignee
                deckId:
                  type: string
                  description: deck ID
                columnId:
                  type: string
                  description: Column ID
              required:
                - id
                - order
                - deckId
                - columnId
      responses:
        200:
          description: The task has been updated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Card"
        400:
          description: Bad request
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          description: Task not found
    delete:
      tags:
        - Card
      summary: Delete Task
      description: Deletes Task by ID.
      responses:
        204:
          description: The task has been deleted
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          description: Task not found
  /login:
    post:
      tags:
        - Auth
      security:
        []
      summary: Login
      description: Logins a user and returns a JWT-token, create refresh token session, set refresh token in http-only cookie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: example
              properties:
                login:
                  type: string
                  description: Username
                password:
                  type: string
                  description: Password
              required:
                - user
                - login
      responses:
        200:
          description: Successful login.
          content:
            application/json:
              schema:
                type: object
                title: example   
                properties:
                  user:
                    type: object
                    description: User data
                    properties:
                      user_id:
                        type: integer
                        description: User id
                      login:
                        type: string
                        description: User login
                      name:
                        type: string
                        description: User name
                  accessToken:
                    type: string
                    description: JWT Access Token
        403:
          description: Forbidden. Bad login/password combination
  /logout:
    post:
      tags:
        - Auth
      security:
        []
      summary: Logout
      description: Logout user and delete refresh token session, send empty cookie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: example
              properties:
                login:
                  type: string
                  description: Username
              required:
                - login
      responses:
        200:
          description: Successful logout.
        400:
          description: Bad Request. Login doesn't exist
  /register:
    post:
      tags:
        - Auth
      security:
        []
      summary: Register
      description: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: example
              properties:
                login:
                  type: string
                  description: Username
                name:
                  type: string
                  description: User nickName
                password:
                  type: string
                  description: Password
              required:
                - name
                - login
                - password
      responses:
        200:
          description: The user has been created.
        400:
          description: Bad Request.
        403:
          description: Incorrect login or password
  /refresh-tokens:
    post:
      tags:
        - Auth
      security:
        []
      summary: Refresh user tokens information
      description: Refresh user tokens information. Get refresh token from Cookie. Delete old refresh token session. Create refresh token session. Send new access token, set in http-only cookie new refresh token.
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              title: example
      responses:
        200:
          description: All new auth data create and send successfully.
          content:
            application/json:
              schema:
                type: object
                title: example   
                properties:
                  user:
                    type: object
                    description: User data
                    properties:
                      user_id:
                        type: integer
                        description: User id
                      login:
                        type: string
                        description: User login
                      name:
                        type: string
                        description: User name
                  accessToken:
                    type: string
                    description: JWT Access Token
        400:
          description: Bad Request.