export const AllCards = [
  {id: 0,
    name: 'agent',
    attack: 5,
    manacost: 2,
    health: 3,
    effect: 'add',
    image_url: 'tdg',
  },
  {id: 1,
    name: 'akama',
    attack: 3,
    manacost: 1,
    health: 2,
    effect: 'add',
    image_url: 'tdg',
  },
  {id: 1,
    name: 'assassinate',
    attack: 0,
    manacost: 1,
    health: 0,
    effect: 'add',
    image_url: 'tdg',
  },
];