export const AllCards = [
  {id: 0,
    name: 'Агент ШРУ',
    isActive: true,
    health: 3,
    attack: 5,
    manaCost: 2,    
    image: 'agent.png',
  },
  {id: 1,
    name: 'Акама',
    isActive: true,
    health: 2,
    attack: 3,
    manaCost: 1,
    image: 'akama.png',
  },
  {id: 2,
    name: 'Ликвидация',
    isActive: false,
    health: 0,
    attack: 0,
    manaCost: 1,
    image: 'assassinate.png',
  },
  {id: 3,
    name: 'Предрешенность',
    isActive: false,
    health: 0,
    attack: 0,
    manaCost: 3,
    image: 'seal_fate.png',
  },
  {id: 4,
    name: 'Заяц',
    isActive: true,
    health: 4,
    attack: 4,
    manaCost: 5,
    image: 'stowaway.png',
  },
  {id: 5,
    name: 'Коварный удар',
    isActive: false,
    health: 0,
    attack: 0,
    manaCost: 5,
    image: 'sinister_strike.png',
  },
  {id: 6,
    name: 'Кошка фараона',
    isActive: true,
    health: 4,
    attack: 4,
    manaCost: 5,
    image: 'pharaoh_cat.png',
  },
  {id: 7,
    name: 'Сластена',
    isActive: true,
    health: 2,
    attack: 3,
    manaCost: 2,
    image: 'sweet_tooth.png',
  },
  {id: 8,
    name: 'Похититель призов',
    isActive: true,
    health: 4,
    attack: 4,
    manaCost: 5,
    image: 'prize_plunderer.png',
  },
  {id: 9,
    name: 'Мастер маскировки',
    isActive: true,
    health: 4,
    attack: 4,
    manaCost: 5,
    image: 'master_disguise.png',
  },
  {id: 10,
    name: 'Вендетта',
    isActive: false,
    health: 0,
    attack: 0,
    manaCost: 5,
    image: 'vendetta.png',
  },
  {id: 11,
    name: 'Коварный удар',
    isActive: false,
    health: 0,
    attack: 0,
    manaCost: 5,
    image: 'sinister_strike.png',
  },
  {id: 12,
    name: 'Кошка фараона',
    isActive: true,
    health: 4,
    attack: 4,
    manaCost: 5,
    image: 'pharaoh_cat.png',
  },
  {id: 13,
    name: 'Сластена',
    isActive: true,
    health: 2,
    attack: 3,
    manaCost: 2,
    image: 'sweet_tooth.png',
  },
  {id: 14,
    name: 'Похититель призов',
    isActive: true,
    health: 4,
    attack: 4,
    manaCost: 5,
    image: 'prize_plunderer.png',
  },
];